import { AcademicSubjectResult, Student } from '../types';
import { getStudents, getSubjectResults, saveStudent, saveSubjectResult } from './storage';
import { AcademicTerm, getChantSubjects } from './schoolSystem';

const RESULT_PUBLICATION_KEY='deacon_system_result_publication_v1';
const SCHOOL_YEARS_ORDER=['الصف الأول الابتدائي','الصف الثاني الابتدائي','الصف الثالث الابتدائي','الصف الرابع الابتدائي','الصف الخامس الابتدائي','الصف السادس الابتدائي','الصف الأول الإعدادي','الصف الثاني الإعدادي','الصف الثالث الإعدادي','الصف الأول الثانوي','الصف الثاني الثانوي','الصف الثالث الثانوي','الجامعة - السنة الأولى','الجامعة - السنة الثانية','الجامعة - السنة الثالثة','الجامعة - السنة الرابعة','خريج / أخرى'];
function schoolLevelForYear(year?:string):string|undefined{if(!year)return undefined;if(year.includes('الابتدائي'))return'المرحلة الابتدائية';if(year.includes('الإعدادي'))return'المرحلة الإعدادية';if(year.includes('الثانوي'))return'المرحلة الثانوية';if(year.includes('الجامعة'))return'المرحلة الجامعية';return'خريج / أخرى';}
export function currentSchoolAcademicYear(date=new Date()):string{const y=date.getFullYear();const start=date.getMonth()>=8?y:y-1;return`${start}/${start+1}`;}
export function nextSchoolYear(year?:string):string|undefined{if(!year)return undefined;const i=SCHOOL_YEARS_ORDER.indexOf(year);return i<0||i>=SCHOOL_YEARS_ORDER.length-1?year:SCHOOL_YEARS_ORDER[i+1];}
/** Kept as a compatibility wrapper. The real annual transition is unified in schoolSystem.ts so a student can never be promoted twice in one cycle. */
export function runAutomaticRegularSchoolPromotion(_force=false):{processed:boolean;advanced:number}{return{processed:false,advanced:0};}
function publicationMap():Record<string,string>{try{return JSON.parse(localStorage.getItem(RESULT_PUBLICATION_KEY)||'{}');}catch{return{};}}
function publicationKey(level:string,year:string,term:AcademicTerm){return`${level}::${year}::${term}`;}
export function publishResults(level:string,year:string,term:AcademicTerm):void{const map=publicationMap();map[publicationKey(level,year,term)]=new Date().toISOString();localStorage.setItem(RESULT_PUBLICATION_KEY,JSON.stringify(map));getSubjectResults().filter((r:AcademicSubjectResult)=>(r.levelName||level)===level&&(r.yearName||year)===year&&r.term===term).forEach(r=>saveSubjectResult({...r,isApproved:true}));window.dispatchEvent(new CustomEvent('deacon_results_published',{detail:{level,year,term}}));}
export function unpublishResults(level:string,year:string,term:AcademicTerm):void{const map=publicationMap();delete map[publicationKey(level,year,term)];localStorage.setItem(RESULT_PUBLICATION_KEY,JSON.stringify(map));getSubjectResults().filter((r:AcademicSubjectResult)=>(r.levelName||level)===level&&(r.yearName||year)===year&&r.term===term).forEach(r=>saveSubjectResult({...r,isApproved:false}));window.dispatchEvent(new CustomEvent('deacon_results_unpublished',{detail:{level,year,term}}));}
export function areResultsPublished(level:string,year:string,term:AcademicTerm):boolean{return!!publicationMap()[publicationKey(level,year,term)];}
export function publishedResultsForStudent(student:Student):AcademicSubjectResult[]{return getSubjectResults(student.id).filter(r=>{const level=r.levelName||student.level,year=r.yearName||student.year,term=r.term as AcademicTerm;return!!term&&areResultsPublished(level,year,term);});}
export function studentPassedBothTerms(student:Student):{passed:boolean;reason:string}{const subjects=getChantSubjects().filter(s=>s.levelName===student.level&&s.yearName===student.year&&s.schoolClass===student.schoolClass);if(!subjects.length)return{passed:false,reason:'لا توجد مواد محددة لهذه السنة والفصل.'};const results=getSubjectResults(student.id).filter(r=>r.levelIndex===student.levelIndex&&r.yearIndex===student.yearIndex);for(const term of ['الترم الأول','الترم الثاني'] as AcademicTerm[]){const termSubjects=subjects.filter(s=>s.term===term);if(!termSubjects.length)return{passed:false,reason:`لا توجد مواد محددة في ${term}.`};for(const subject of termSubjects){const result=results.find(r=>r.subjectName===subject.name&&r.term===term);if(!result)return{passed:false,reason:`لم تُرصد نتيجة ${subject.name} في ${term}.`};const pct=result.maxScore>0?(result.score/result.maxScore)*100:0;if(pct<50)return{passed:false,reason:`الطالب أقل من 50% في ${subject.name} في ${term}.`};}}return{passed:true,reason:'ناجح في جميع مواد الترمين.'};}
