import { collection, deleteDoc, doc, getDocs, setDoc } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { AcademicSubjectResult, Lecture, LiturgyAttendance, Servant, Student } from '../types';
import { getAcademicLevels, getAcademicYears, getLiturgyAttendances, getStudents, getSubjectResults, getServants, getLectures, saveStudent } from './storage';
import { normalizeSchoolClass } from './schoolClassUtils';
import { egyptDateString, isEgyptFriday } from './egyptTime';

export type AcademicTerm = 'الترم الأول' | 'الترم الثاني';
export interface ChantSubject { id:string; name:string; levelName:string; yearName:string; schoolClass?:string; term:AcademicTerm; createdAt:string; createdBy:string; }
export interface AnnualStudentSnapshot { academicYear:string; schoolLevel?:string; schoolYear?:string; chantLevel:string; chantYear:string; levelIndex:number; yearIndex:number; archivedAt:string; }

const SUBJECTS_KEY='deacon_system_chant_subjects_v2';
const LAST_TRANSITION_KEY='deacon_system_last_academic_transition_v3';
const PROMOTION_LOCK_KEY='deacon_system_promotion_lock_v3';
const SCHOOL_YEARS_ORDER=['الصف الأول الابتدائي','الصف الثاني الابتدائي','الصف الثالث الابتدائي','الصف الرابع الابتدائي','الصف الخامس الابتدائي','الصف السادس الابتدائي','الصف الأول الإعدادي','الصف الثاني الإعدادي','الصف الثالث الإعدادي','الصف الأول الثانوي','الصف الثاني الثانوي','الصف الثالث الثانوي','الجامعة - السنة الأولى','الجامعة - السنة الثانية','الجامعة - السنة الثالثة','الجامعة - السنة الرابعة','خريج / أخرى'];

export function currentAcademicYear(date=new Date()):string { const y=date.getFullYear(); const start=date.getMonth()>=8?y:y-1; return `${start}/${start+1}`; }
export function academicYearStart(year=currentAcademicYear()):Date { const start=Number(year.split('/')[0])||new Date().getFullYear(); return new Date(start,8,1); }
function schoolLevelForYear(year?:string):string|undefined { if(!year)return undefined; if(year.includes('الابتدائي'))return 'المرحلة الابتدائية'; if(year.includes('الإعدادي'))return 'المرحلة الإعدادية'; if(year.includes('الثانوي'))return 'المرحلة الثانوية'; if(year.includes('الجامعة'))return 'المرحلة الجامعية'; return 'خريج / أخرى'; }
export function nextRegularSchoolYear(year?:string):string|undefined { if(!year)return year; const i=SCHOOL_YEARS_ORDER.indexOf(year); return i<0||i>=SCHOOL_YEARS_ORDER.length-1?year:SCHOOL_YEARS_ORDER[i+1]; }

export function getChantSubjects():ChantSubject[]{try{const raw=localStorage.getItem(SUBJECTS_KEY);const list=raw?JSON.parse(raw):[];return Array.isArray(list)?list.map((s:ChantSubject)=>({...s,schoolClass:normalizeSchoolClass(s.schoolClass)})):[];}catch{return[];}}
function saveSubjectsLocal(list:ChantSubject[]){localStorage.setItem(SUBJECTS_KEY,JSON.stringify(list));window.dispatchEvent(new CustomEvent('deacon_data_updated',{detail:{source:'subjects'}}));}
export async function refreshSubjectsFromFirebase():Promise<ChantSubject[]>{try{const snap=await getDocs(collection(db,'chantSubjects'));const list=snap.docs.map(d=>{const x=d.data() as ChantSubject;return {...x,schoolClass:normalizeSchoolClass(x.schoolClass)};});if(list.length)saveSubjectsLocal(list);return getChantSubjects();}catch{return getChantSubjects();}}
export async function saveChantSubject(input:Partial<ChantSubject>):Promise<ChantSubject>{const list=getChantSubjects();const name=(input.name||'').trim();const schoolClass=normalizeSchoolClass(input.schoolClass);if(!name||!input.levelName||!input.yearName||!schoolClass||!input.term)throw new Error('بيانات المادة غير مكتملة.');const duplicate=list.find(s=>s.id!==input.id&&s.name.trim()===name&&s.levelName===input.levelName&&s.yearName===input.yearName&&normalizeSchoolClass(s.schoolClass)===schoolClass&&s.term===input.term);if(duplicate)throw new Error('هذه المادة موجودة بالفعل.');const item:ChantSubject={id:input.id||`sub-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name,levelName:input.levelName!,yearName:input.yearName!,schoolClass,term:input.term!,createdAt:input.createdAt||new Date().toISOString(),createdBy:input.createdBy||'الإدارة'};const i=list.findIndex(s=>s.id===item.id);if(i>=0)list[i]=item;else list.push(item);saveSubjectsLocal(list);try{await setDoc(doc(db,'chantSubjects',item.id),item,{merge:true});}catch{}return item;}
export async function deleteChantSubject(id:string){saveSubjectsLocal(getChantSubjects().filter(s=>s.id!==id));try{await deleteDoc(doc(db,'chantSubjects',id));}catch{}}
export function subjectsForStudent(student:Student,term:AcademicTerm){return getChantSubjects().filter(s=>s.levelName===student.level&&s.yearName===student.year&&normalizeSchoolClass(s.schoolClass)===normalizeSchoolClass(student.schoolClass)&&s.term===term);}
export function resultsForStudentTerm(studentId:string,levelIndex:number,yearIndex:number,term:AcademicTerm):AcademicSubjectResult[]{return getSubjectResults(studentId).filter(r=>r.levelIndex===levelIndex&&r.yearIndex===yearIndex&&r.term===term);}
export function chantYearPassStatus(student:Student){const required=getChantSubjects().filter(s=>s.levelName===student.level&&s.yearName===student.year&&normalizeSchoolClass(s.schoolClass)===normalizeSchoolClass(student.schoolClass));if(!required.length)return{passed:false,reason:'لا توجد مواد محددة لهذه السنة بعد.',required:0,completed:0};const results=getSubjectResults(student.id).filter(r=>r.levelIndex===student.levelIndex&&r.yearIndex===student.yearIndex);let completed=0;for(const subject of required){const result=results.find(r=>r.subjectName===subject.name&&r.term===subject.term);if(!result)return{passed:false,reason:`لم يتم رصد نتيجة مادة ${subject.name} - ${subject.term}.`,required:required.length,completed};completed++;const pct=result.maxScore>0?(result.score/result.maxScore)*100:0;if(pct<50)return{passed:false,reason:`الطالب أقل من 50% في مادة ${subject.name} - ${subject.term}.`,required:required.length,completed};}return{passed:true,reason:'ناجح في جميع المواد بنسبة 50% أو أكثر.',required:required.length,completed};}
function advanceChantStage(student:Student,graduationAcademicYear?:string):Student{const levels=getAcademicLevels(),years=getAcademicYears(),history=Array.isArray(student.history)?[...student.history]:[];const current=history.find(h=>h.levelIndex===student.levelIndex&&h.yearIndex===student.yearIndex);if(current){current.status='passed';current.archivedAt=new Date().toISOString();}let nextL=student.levelIndex,nextY=student.yearIndex+1;if(nextY>=years.length){nextY=0;nextL++;}if(nextL>=levels.length){const endYear=Number((graduationAcademicYear||currentAcademicYear()).split('/')[1]);return{...student,history,graduationYear:Number.isFinite(endYear)?endYear:new Date().getFullYear(),graduatedAt:new Date().toISOString()};}return{...student,levelIndex:nextL,yearIndex:nextY,level:levels[nextL],year:years[nextY],history,graduationYear:undefined,graduatedAt:undefined};}

/** One idempotent annual transition. Regular school always advances; chant school advances only when every configured subject is >=50%. */
export async function runAutomaticAcademicTransition(force=false):Promise<{processed:boolean;schoolAdvanced:number;chantAdvanced:number;chantHeld:number}>{const year=currentAcademicYear();const last=localStorage.getItem(LAST_TRANSITION_KEY);if(!force&&!last){localStorage.setItem(LAST_TRANSITION_KEY,year);return{processed:false,schoolAdvanced:0,chantAdvanced:0,chantHeld:0};}if(!force&&last===year)return{processed:false,schoolAdvanced:0,chantAdvanced:0,chantHeld:0};const cycle=last||year;if(localStorage.getItem(PROMOTION_LOCK_KEY)===cycle&&!force)return{processed:false,schoolAdvanced:0,chantAdvanced:0,chantHeld:0};let schoolAdvanced=0,chantAdvanced=0,chantHeld=0;for(const original of getStudents(true).filter(s=>!s.isDeleted)){const annualHistory=Array.isArray(original.annualHistory)?[...original.annualHistory]:[];if(!annualHistory.some(h=>h.academicYear===cycle))annualHistory.push({academicYear:cycle,schoolLevel:original.schoolLevel,schoolYear:original.schoolYear,chantLevel:original.level,chantYear:original.year,levelIndex:original.levelIndex,yearIndex:original.yearIndex,archivedAt:new Date().toISOString()});let updated:Student={...original,annualHistory};const nextSchool=nextRegularSchoolYear(original.schoolYear);if(nextSchool&&nextSchool!==original.schoolYear){updated.schoolYear=nextSchool;updated.schoolLevel=schoolLevelForYear(nextSchool);schoolAdvanced++;}const status=chantYearPassStatus(original);if(status.passed){const promoted=advanceChantStage(updated,cycle);if(promoted.levelIndex!==updated.levelIndex||promoted.yearIndex!==updated.yearIndex)chantAdvanced++;updated=promoted;}else chantHeld++;saveStudent(updated);}localStorage.setItem(PROMOTION_LOCK_KEY,cycle);localStorage.setItem(LAST_TRANSITION_KEY,year);return{processed:true,schoolAdvanced,chantAdvanced,chantHeld};}

export function getFridayDates(from=academicYearStart(),to=new Date()):string[]{const cursor=new Date(from);cursor.setHours(0,0,0,0);while(!isEgyptFriday(cursor))cursor.setDate(cursor.getDate()+1);const end=new Date(to);end.setHours(23,59,59,999);const out:string[]=[];while(cursor<=end){out.push(egyptDateString(cursor));cursor.setDate(cursor.getDate()+7);}return out;}
export function dedupedLiturgyAttendances():LiturgyAttendance[]{const map=new Map<string,LiturgyAttendance>();for(const rec of getLiturgyAttendances()){const key=`${rec.studentId}::${rec.dateStr}`;const current=map.get(key);if(!current||rec.timestamp<current.timestamp)map.set(key,rec);}return[...map.values()];}

/** Friday attendance: every Friday in the academic period is counted; a missing record is an absence. */
export function fridayAttendanceSummary(studentId:string,from=academicYearStart(),to=new Date()){const dates=getFridayDates(from,to);const records=new Set(dedupedLiturgyAttendances().filter(r=>r.studentId===studentId&&dates.includes(r.dateStr)).map(r=>r.dateStr));const attended=dates.filter(d=>records.has(d)).length;return{totalFridays:dates.length,attended,absent:dates.length-attended,percentage:dates.length?Math.round(attended/dates.length*100):0,dates};}
export function recordFridayAttendance(student:Student,recordedBy:string,recordedByName:string,date=new Date()){const dateStr=egyptDateString(date);if(!isEgyptFriday(date)) return{ok:false,message:'تسجيل حضور القداس متاح يوم الجمعة فقط.'};const existing=dedupedLiturgyAttendances().find(r=>r.studentId===student.id&&r.dateStr===dateStr);if(existing)return{ok:false,message:'تم تسجيل حضور الطالب لهذا الجمعة بالفعل.'};const record:LiturgyAttendance={id:`lit-${student.id}-${dateStr}`,studentId:student.id,studentCode:student.studentCode,studentName:student.fullName,studentRank:student.deaconRank,timestamp:date.toISOString(),dateStr,timeStr:date.toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Africa/Cairo'}),recordedBy,recordedByName};try{localStorage.setItem('deacon_system_liturgies_v1',JSON.stringify([...getLiturgyAttendances().filter(r=>!(r.studentId===student.id&&r.dateStr===dateStr)),record]));window.dispatchEvent(new CustomEvent('deacon_data_updated',{detail:{source:'liturgy'}}));}catch{}return{ok:true,message:`تم تسجيل حضور ${student.fullName} في قداس الجمعة.`};}

export function isAllowedLecturer(servant?:Servant|null):boolean{return !!servant&&servant.isActive&&(servant.role==='senior_servant'||servant.role==='admin')&&servant.permissions?.canTeachLectures!==false;}
export function canEvaluateLecture(lecture:Lecture,userId?:string,isAdmin=false):boolean{return !!lecture&&!!userId&&(isAdmin||lecture.speakerServantId===userId);}
export function lecturesNeedingEvaluation(lectures:Lecture[]=getLectures(),userId?:string,isAdmin=false):Lecture[]{return lectures.filter(l=>l.status==='elapsed'&&!l.isEvaluated&&canEvaluateLecture(l,userId,isAdmin));}
