import { syncStudentToCloud, deleteStudentFromCloud, syncServantToCloud, deleteServantFromCloud, syncLiturgyAttendanceToCloud, syncLectureToCloud, deleteLectureFromCloud, syncLectureAttendanceToCloud, syncSubjectResultToCloud, deleteSubjectResultFromCloud, syncBehaviorNoteToCloud, syncAcademicSettingsToCloud, syncCurriculumToCloud, deleteCurriculumFromCloud, fetchAllDataFromFirebase, syncSchoolLogoToCloud, syncChantSubjectToCloud, deleteChantSubjectFromCloud } from './firebaseService';

export type MutationType = 'save_student'|'delete_student'|'save_servant'|'delete_servant'|'save_liturgy'|'save_lecture'|'delete_lecture'|'save_lecture_attendance'|'save_subject_result'|'delete_subject_result'|'save_behavior_note'|'save_academic_settings'|'save_curriculum'|'delete_curriculum'|'save_school_logo'|'save_chant_subject'|'delete_chant_subject';
export interface OfflineMutation { id:string; type:MutationType; payload:any; timestamp:number; retryCount:number; }
export interface SyncStatus { isOnline:boolean; state:'idle'|'syncing'|'synced'|'offline'|'error'; pendingCount:number; lastSyncedAt:string|null; errorMessage?:string; }
const STORAGE_KEYS={QUEUE:'deacon_offline_sync_queue_v1',LAST_SYNC:'deacon_last_synced_at_v1'};
const listeners=new Set<(status:SyncStatus)=>void>();
let isCurrentlySyncing=false;
export function getIsOnline(){ return typeof navigator==='undefined'?true:navigator.onLine; }
export function getPendingQueue():OfflineMutation[]{ try{const raw=localStorage.getItem(STORAGE_KEYS.QUEUE);return raw?JSON.parse(raw):[];}catch(err){console.error('Failed to read offline queue:',err);return[];} }
function saveQueue(queue:OfflineMutation[]){try{localStorage.setItem(STORAGE_KEYS.QUEUE,JSON.stringify(queue));notifyStatusChange();}catch(err){console.error('Failed to save offline queue:',err);}}
export function enqueueMutation(type:MutationType,payload:any){const queue=getPendingQueue();let filtered=queue;if(payload&&payload.id&&type.startsWith('save_'))filtered=queue.filter(m=>!(m.type===type&&m.payload?.id===payload.id));filtered.push({id:`mut-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,type,payload,timestamp:Date.now(),retryCount:0});saveQueue(filtered);if(getIsOnline())processSyncQueue().catch(err=>console.warn('Background sync trigger:',err));}
export function getSyncStatus():SyncStatus{const queue=getPendingQueue();const online=getIsOnline();const lastSyncedAt=localStorage.getItem(STORAGE_KEYS.LAST_SYNC);let state:SyncStatus['state']='idle';if(!online)state='offline';else if(isCurrentlySyncing)state='syncing';else if(queue.length===0)state='synced';return{isOnline:online,state,pendingCount:queue.length,lastSyncedAt};}
function notifyStatusChange(errorMessage?:string){const status=getSyncStatus();if(errorMessage)status.errorMessage=errorMessage;listeners.forEach(cb=>{try{cb(status);}catch(e){console.warn('Sync status listener error:',e);}});if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('deacon_sync_status_changed',{detail:status}));}
export function subscribeToSyncStatus(callback:(status:SyncStatus)=>void){listeners.add(callback);callback(getSyncStatus());return()=>listeners.delete(callback);}
async function executeMutation(m:OfflineMutation){switch(m.type){case'save_student':await syncStudentToCloud(m.payload);break;case'delete_student':await deleteStudentFromCloud(m.payload);break;case'save_servant':await syncServantToCloud(m.payload);break;case'delete_servant':await deleteServantFromCloud(m.payload);break;case'save_liturgy':await syncLiturgyAttendanceToCloud(m.payload);break;case'save_lecture':await syncLectureToCloud(m.payload);break;case'delete_lecture':await deleteLectureFromCloud(m.payload);break;case'save_lecture_attendance':await syncLectureAttendanceToCloud(m.payload);break;case'save_subject_result':await syncSubjectResultToCloud(m.payload);break;case'delete_subject_result':await deleteSubjectResultFromCloud(m.payload);break;case'save_behavior_note':await syncBehaviorNoteToCloud(m.payload);break;case'save_academic_settings':await syncAcademicSettingsToCloud(m.payload.levels,m.payload.years);break;case'save_curriculum':await syncCurriculumToCloud(m.payload);break;case'delete_curriculum':await deleteCurriculumFromCloud(m.payload);break;case'save_school_logo':await syncSchoolLogoToCloud(m.payload);break;case'save_chant_subject':await syncChantSubjectToCloud(m.payload);break;case'delete_chant_subject':await deleteChantSubjectFromCloud(m.payload);break;default:throw new Error(`Unknown mutation type: ${(m as any).type}`);}}
export async function processSyncQueue(){if(isCurrentlySyncing)return{processed:0,remaining:getPendingQueue().length};if(!getIsOnline()){notifyStatusChange();return{processed:0,remaining:getPendingQueue().length};}isCurrentlySyncing=true;notifyStatusChange();const queue=getPendingQueue();if(queue.length===0){isCurrentlySyncing=false;localStorage.setItem(STORAGE_KEYS.LAST_SYNC,new Date().toISOString());notifyStatusChange();return{processed:0,remaining:0};}let processed=0;const remaining:OfflineMutation[]=[];for(const mutation of queue){try{await executeMutation(mutation);processed++;}catch(err){console.warn(`Failed to sync mutation ${mutation.type}:`,err);mutation.retryCount=(mutation.retryCount||0)+1;remaining.push(mutation);}}saveQueue(remaining);if(remaining.length===0)localStorage.setItem(STORAGE_KEYS.LAST_SYNC,new Date().toISOString());isCurrentlySyncing=false;notifyStatusChange();return{processed,remaining:remaining.length};}
export async function triggerFullSync(onPullComplete?:(data:any)=>void){if(!getIsOnline())return{success:false,message:'الجهاز غير متصل بالإنترنت حالياً. سيتم المزامنة تلقائياً عند الاتصال.'};try{const{processed}=await processSyncQueue();const cloudData=await fetchAllDataFromFirebase();if(cloudData&&onPullComplete)onPullComplete(cloudData);localStorage.setItem(STORAGE_KEYS.LAST_SYNC,new Date().toISOString());window.dispatchEvent(new CustomEvent('deacon_data_updated',{detail:{source:'cloud_sync'}}));return{success:true,message:processed>0?`تم رفع ${processed} تعديلات بنجاح ومزامنة أحدث البيانات السحابية!`:'تم التحقق من الاتصال وجميع البيانات متطابقة ومحدثة سحابياً.'};}catch(err:any){isCurrentlySyncing=false;notifyStatusChange(err?.message||'حدث خطأ أثناء المزامنة');return{success:false,message:'تعذرت المزامنة، سيتم المحاولة مجدداً.'};}}
export function initOfflineSyncListeners(onDataPulled?:(data:any)=>void){if(typeof window==='undefined')return;const handleOnline=()=>{notifyStatusChange();setTimeout(()=>triggerFullSync(onDataPulled),1000);};const handleOffline=()=>notifyStatusChange();window.addEventListener('online',handleOnline);window.addEventListener('offline',handleOffline);const interval=setInterval(()=>{if(getIsOnline()&&getPendingQueue().length>0&&!isCurrentlySyncing)processSyncQueue();},15000);const handleVisibility=()=>{if(document.visibilityState==='visible'&&getIsOnline()&&getPendingQueue().length>0)processSyncQueue();};document.addEventListener('visibilitychange',handleVisibility);return()=>{window.removeEventListener('online',handleOnline);window.removeEventListener('offline',handleOffline);clearInterval(interval);document.removeEventListener('visibilitychange',handleVisibility);};}
