import React, { useMemo, useState } from 'react';
import { GraduationCap, UserPlus, CheckCircle2 } from 'lucide-react';
import { DeaconRank, Student, UserSession } from '../types';
import { DEACON_RANKS, SCHOOL_LEVELS, SCHOOL_YEARS, getAcademicLevels, getAcademicYears, saveStudent } from '../services/storage';
import { SmartIDCardModal } from './SmartIDCardModal';
interface Props { session: UserSession; }
export const AddStudentModule: React.FC<Props> = ({ session }) => {
 const levels=useMemo(()=>getAcademicLevels(),[]), years=useMemo(()=>getAcademicYears(),[]);
 const canEdit=session.role==='admin'||!!session.permissions?.canAddEditStudents;
 const makeForm=()=>({fullName:'',photoUrl:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',deaconRank:'إبصالتس' as DeaconRank,level:levels[0]||'المستوى الأول',year:years[0]||'السنة الأولى',levelIndex:0,yearIndex:0,schoolLevel:SCHOOL_LEVELS[0]||'',schoolYear:SCHOOL_YEARS[0]||'',nationalId:'',phone:'',guardianPhone:'',notes:''});
 const [form,setForm]=useState(makeForm),[saved,setSaved]=useState<string|null>(null),[error,setError]=useState(''),[savedStudent,setSavedStudent]=useState<Student|null>(null);
 const set=(k:string,v:string)=>setForm(p=>({...p,[k]:v}));
 const submit=(e:React.FormEvent)=>{e.preventDefault();setError('');setSaved(null);try{const levelIndex=Math.max(0,levels.indexOf(form.level)),yearIndex=Math.max(0,years.indexOf(form.year));const student=saveStudent({...form,levelIndex,yearIndex});setSaved(`تم حفظ بيانات الطالب «${student.fullName}» بنجاح — كود الطالب: ${student.studentCode}`);setSavedStudent(student);setForm(makeForm());}catch(err){setError(err instanceof Error?err.message:'تعذر حفظ الطالب.');}};
 if(!canEdit)return <div className="bg-slate-900 border border-slate-800 rounded-3xl p-10 text-center"><GraduationCap className="w-12 h-12 mx-auto text-amber-500 mb-3"/><h2 className="text-lg font-black">إضافة الطلاب</h2><p className="text-xs text-slate-400 mt-2">هذه الوظيفة غير متاحة لحسابك.</p></div>;
 return <div className="space-y-6"><div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl"><h2 className="text-xl font-black text-slate-100 flex items-center gap-2"><GraduationCap className="w-6 h-6 text-amber-400"/>إضافة طالب جديد بالمدرسة</h2><p className="text-xs text-slate-400 mt-1">نموذج إضافة الطالب القديم — كود الطالب يتم إنشاؤه تلقائياً.</p></div>
 {saved&&<div className="bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 rounded-2xl p-4 text-sm font-bold flex items-center gap-2"><CheckCircle2 className="w-5 h-5"/>{saved}</div>}{error&&<div className="bg-rose-500/10 border border-rose-500/30 text-rose-300 rounded-2xl p-4 text-xs font-bold">{error}</div>}
 <form onSubmit={submit} className="bg-slate-900 border border-slate-700 rounded-3xl p-6 shadow-2xl space-y-4 text-xs"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
 <div className="sm:col-span-2"><label className="label">الاسم الرباعي كاملاً: <span className="text-rose-400">*</span></label><input required value={form.fullName} onChange={e=>set('fullName',e.target.value)} placeholder="مثال: يوحنا سمير حنا فهمي" className="field"/></div>
 <div className="sm:col-span-2"><label className="label">رابط الصورة الشخصية (Photo URL):</label><div className="flex gap-2"><input type="url" value={form.photoUrl} onChange={e=>set('photoUrl',e.target.value)} className="field"/><img src={form.photoUrl} alt="معاينة" className="w-9 h-9 rounded-xl object-cover ring-1 ring-amber-500/40 shrink-0"/></div></div>
 <div><label className="label">الرتبة الشماسية:</label><select value={form.deaconRank} onChange={e=>set('deaconRank',e.target.value)} className="field">{DEACON_RANKS.map(r=><option key={r}>{r}</option>)}</select></div>
 <div><label className="label">الرقم القومي (14 رقم):</label><input maxLength={14} value={form.nationalId} onChange={e=>set('nationalId',e.target.value)} placeholder="30201011234567" className="field font-mono"/></div>
 <div className="sm:col-span-2 pt-2 border-t border-slate-800"><span className="text-xs font-bold text-amber-400 block mb-2">🎓 بيانات مدرسة الشمامسة (بالخدمة):</span></div>
 <div><label className="label">المرحلة الدراسية بالخدمة (المستوى):</label><select value={form.level} onChange={e=>{const v=e.target.value;setForm(p=>({...p,level:v,levelIndex:Math.max(0,levels.indexOf(v))}))}} className="field">{levels.map(x=><option key={x}>{x}</option>)}</select></div>
 <div><label className="label">السنة الدراسية بالخدمة:</label><select value={form.year} onChange={e=>{const v=e.target.value;setForm(p=>({...p,year:v,yearIndex:Math.max(0,years.indexOf(v))}))}} className="field">{years.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="sm:col-span-2 pt-2 border-t border-slate-800"><span className="text-xs font-bold text-sky-400 block mb-2">🏫 بيانات التعليم والمدرسة (المدرسة العادية):</span></div>
 <div><label className="label">المرحلة الدراسية بالمدرسة:</label><select value={form.schoolLevel} onChange={e=>set('schoolLevel',e.target.value)} className="field">{SCHOOL_LEVELS.map(x=><option key={x}>{x}</option>)}</select></div>
 <div><label className="label">السنة الدراسية بالمدرسة:</label><select value={form.schoolYear} onChange={e=>set('schoolYear',e.target.value)} className="field">{SCHOOL_YEARS.map(x=><option key={x}>{x}</option>)}</select></div>
 <div><label className="label">هاتف الطالب الشخصي:</label><input value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="01200000000" className="field font-mono"/></div>
 <div><label className="label">هاتف ولي الأمر (الطوارئ):</label><input value={form.guardianPhone} onChange={e=>set('guardianPhone',e.target.value)} placeholder="01000000000" className="field font-mono"/></div>
 <div className="sm:col-span-2"><label className="label">ملاحظات وقيد الخادم:</label><textarea rows={2} value={form.notes} onChange={e=>set('notes',e.target.value)} className="field resize-none"/></div></div>
 <div className="flex justify-end pt-4 border-t border-slate-800"><button type="submit" className="px-6 py-2 bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold rounded-xl shadow-md flex items-center gap-2"><UserPlus className="w-4 h-4"/>حفظ البيانات</button></div></form>
 <style>{`.label{display:block;color:#cbd5e1;font-weight:600;margin-bottom:.25rem}.field{width:100%;background:#020617;border:1px solid #1e293b;border-radius:.75rem;padding:.5rem .75rem;color:#f1f5f9;outline:none}.field:focus{border-color:#f59e0b}`}</style>
 <SmartIDCardModal student={savedStudent} isOpen={!!savedStudent} onClose={()=>setSavedStudent(null)}/></div>;
};