import React, { useState } from 'react';
import { BookOpen, QrCode, CheckCircle2, AlertTriangle, Clock } from 'lucide-react';
import { Lecture, LectureAttendance, UserSession } from '../types';
import { getLectures, getLectureAttendances, recordLectureAttendance, getStudents } from '../services/storage';
import { QRScannerModal } from './QRScannerModal';
import { sessionHasPermission } from '../services/permissions';

export const LectureAttendanceLimitedModule: React.FC<{session: UserSession}> = ({session}) => {
 const [lectures,setLectures]=useState<Lecture[]>(()=>getLectures());
 const [attendance,setAttendance]=useState<LectureAttendance[]>(()=>getLectureAttendances());
 const [scanner,setScanner]=useState(false); const [selectedId,setSelectedId]=useState(''); const [message,setMessage]=useState<string|null>(null);
 const canRecord=sessionHasPermission(session,'canRecordAttendance'); const active=lectures.filter(l=>l.status==='active'); const selected=active.find(l=>l.id===selectedId)||active[0];
 const refresh=()=>{setLectures(getLectures());setAttendance(getLectureAttendances());};
 const scan=(text:string)=>{if(!canRecord){setMessage('لا توجد لديك صلاحية تسجيل الحضور.');return;}const clean=text.trim().toLowerCase();const stu=getStudents().find(s=>s.studentCode.toLowerCase()===clean||s.nationalId===clean||s.id.toLowerCase()===clean);if(!stu){setMessage('كود الطالب غير موجود.');return;}if(!selected){setMessage('لا توجد محاضرة نشطة حالياً.');return;}const r=recordLectureAttendance(selected.id,stu,'committed',undefined,session.userId||'servant',session.fullName||'الخادم');setMessage(r.message);refresh();setTimeout(()=>setMessage(null),3000);};
 return <div className="space-y-6"><div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl"><div className="flex items-center gap-3"><div className="p-3 bg-amber-500/20 rounded-2xl"><BookOpen className="w-6 h-6 text-amber-400"/></div><div><h2 className="text-xl font-black">حضور المحاضرات</h2><p className="text-xs text-slate-400">تسجيل الحضور والغياب متاح لجميع الخدام. التقييمات الإدارية غير متاحة لهذا الحساب.</p></div></div></div>{message&&<div className="p-4 bg-emerald-500/10 border border-emerald-500/30 rounded-2xl text-emerald-300 text-xs font-bold"><CheckCircle2 className="w-4 h-4 inline ml-2"/>{message}</div>}<div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl"><h3 className="font-bold text-slate-100 mb-3">المحاضرات النشطة</h3>{active.length===0?<div className="text-center text-slate-500 p-8"><Clock className="w-10 h-10 mx-auto mb-2"/>لا توجد محاضرات نشطة حالياً.</div>:<div className="grid md:grid-cols-2 gap-3">{active.map(l=><button key={l.id} onClick={()=>setSelectedId(l.id)} className={`text-right p-4 rounded-2xl border ${selected?.id===l.id?'border-amber-500 bg-amber-500/10':'border-slate-800 bg-slate-950'}`}><b>{l.title}</b><span className="block text-xs text-amber-400 mt-1">{l.levelName}</span><span className="block text-[10px] text-slate-500 mt-1">{l.dateStr} · {l.timeStr}</span></button>)}</div>}</div>{selected&&<div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 text-center shadow-xl"><h3 className="text-lg font-bold">تسجيل حضور: {selected.title}</h3><p className="text-xs text-slate-400 mt-1 mb-5">امسح بطاقة الطالب لتسجيل حضوره.</p><button disabled={!canRecord} onClick={()=>setScanner(true)} className="px-8 py-4 bg-amber-500 disabled:opacity-40 text-slate-950 font-black rounded-2xl inline-flex items-center gap-2"><QrCode className="w-5 h-5"/>{canRecord?'مسح QR Code':'التسجيل غير متاح'}</button></div>}<div className="bg-slate-900 border border-slate-800 rounded-3xl p-6"><h3 className="font-bold mb-3">سجل الحضور</h3><div className="space-y-2">{attendance.filter(a=>!selected||a.lectureId===selected.id).map(a=><div key={a.id} className="p-3 bg-slate-950 rounded-xl text-xs flex justify-between"><span>{a.studentName}</span><span className="text-emerald-400">{a.status==='late'?`متأخر ${a.lateMinutes||0} دقيقة`:'حاضر'}</span></div>)}{attendance.filter(a=>!selected||a.lectureId===selected.id).length===0&&<p className="text-center text-slate-500 text-xs p-5">لا يوجد حضور مسجل بعد.</p>}</div></div><QRScannerModal isOpen={scanner} onClose={()=>setScanner(false)} onScanSuccess={scan} title="مسح بطاقة الطالب للحضور"/></div>;
};
